driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: debian-9
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-16.04-chef-12.9
    driver_config:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12.9.41

suites:
  - name: default
    run_list:
      - recipe[apt]

  - name: cacher
    run_list:
      - recipe[test::cacher]
    excludes: centos-7

  - name: compile-time
    run_list:
      - recipe[apt::default]
    attributes:
      apt:
        compile_time_update: true
    excludes: centos-7

  - name: resources
    run_list:
      - recipe[test::resources]
    excludes: centos-7

  - name: unattended-upgrades
    run_list:
      - recipe[test::unattended-upgrades]
    attributes:
      apt:
        unattended_upgrades:
          enable: true
    excludes: centos-7
