AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

MethodLength:
  Max: 25

CyclomaticComplexity:
  Max: 7

ParameterLists:
  Enabled: false