name              'apt'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Configures apt and apt caching.'
version           '7.5.22'
source_url        'https://github.com/sous-chefs/apt'
issues_url        'https://github.com/sous-chefs/apt/issues'
chef_version      '>= 13.3'

supports 'debian'
supports 'ubuntu'
