name              'apt'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides apt_config, apt_cacher_client, apt_cacher_ng, and apt_unattended_upgrades resources.'
version           '7.7.0'
source_url        'https://github.com/sous-chefs/apt'
issues_url        'https://github.com/sous-chefs/apt/issues'
chef_version      '>= 15.3'

supports 'debian', '>= 12.0'
supports 'ubuntu', '>= 22.04'
