name              'rackspace_apt_test'
maintainer        'Rackspace, US Inc.'
maintainer_email  'rackspace-cookbooks@rackspace.com'
license           'Apache 2.0'
description       'This cookbook is used with test-kitchen to test the parent, apt cookbok'
version           '1.0.0'
