default[:rackspace_apt][:config][:acng][:CacheDir] = "/var/cache/apt-cacher-ng"
default[:rackspace_apt][:config][:acng][:LogDir] = "/var/log/apt-cacher-ng"
default[:rackspace_apt][:config][:acng][:Port] = "3142"
default[:rackspace_apt][:config][:acng][:'Remap-debrep'] = "file:deb_mirror*.gz /debian ; file:backends_debian"
default[:rackspace_apt][:config][:acng][:'Remap-uburep'] = "file:ubuntu_mirrors /ubuntu ; file:backends_ubuntu"
default[:rackspace_apt][:config][:acng][:'Remap-debvol'] = "file:debvol_mirror*.gz /debian-volatile ; file:backends_debvol"
default[:rackspace_apt][:config][:acng][:'Remap-cygwin'] = "file:cygwin_mirrors /cygwin"
default[:rackspace_apt][:config][:acng][:'Remap-sfnet'] = "file:sfnet_mirrors"
default[:rackspace_apt][:config][:acng][:'Remap-alxrep'] = "file:archlx_mirrors /archlinux"
default[:rackspace_apt][:config][:acng][:'Remap-fedora'] = "file:fedora_mirrors"
default[:rackspace_apt][:config][:acng][:'Remap-epel'] = "file:epel_mirrors" 
default[:rackspace_apt][:config][:acng][:'Remap-slrep'] = "file:sl_mirrors"
default[:rackspace_apt][:config][:acng][:ReportPage] = "acng-report.html"
default[:rackspace_apt][:config][:acng][:ExTreshold] = "4"
default[:rackspace_apt][:config][:'01proxy']['cache_bypass'] = {}
default[:rackspace_apt][:switch][:'cacher-client'][:restrict_environment] = false
default[:rackspace_apt][:switch][:cacher_interface] = nil
default[:rackspace_apt][:switch][:caching_server] = false
default[:rackspace_apt][:switch][:compiletime] = false
default[:rackspace_apt]['key_proxy'] = ''
